#!/usr/bin/env python

import sys
import os
import shutil
import openUapp
from os.path import isfile

uApp = openUapp.repo()
uAppLocal = openUapp.local()

def usage():
	print 'Usage:'	
	print 'open-uapp update [app ID] [keys splited by ,] "[values splited by , (in the same order as keys)]" | Edit an app'
	print 'open-uapp new | Create a new app'
	print 'open-uapp delete [app ID] | Delete an App'
	print 'open-uapp list | List all Apps'
	print 'open-uapp info [app ID] Displays info about an App'
	print ' '
	print 'Examples:'
	print 'open-uapp update openstore.mzanetti name,version,pakage "testapp,0.1,build/package"'
	print 'open-uapp new'
	print 'open-uapp delete openstore.mzanetti'
	print 'open-uapp list'
	print 'open-uapp info openstore.mzanetti'
	
	sys.exit()

if len(sys.argv) <= 1:
	usage()
elif sys.argv[1] == "keys":
	print "license, source, description, category, tagline"
elif sys.argv[1] == "update":
	if len(sys.argv) > 2:
		if not uApp.hasApi():
			print "You have not provided a API key"
			print "Use 'open-uapp config api [key]' to set the api key"
			sys.exit()
		if not uApp.idExist(sys.argv[2]):
			print "The ID " + sys.argv[2] + " does not exsist"
			sys.exit()
		arggs=sys.argv[3].split(",")
		values=sys.argv[4].split(",")
		gotOne=False
		i=0
		for argg in arggs:
			elif argg == "license":
				uApp.update["license"] = values[i] 
				gotOne=True
			elif argg == "tagline":
				uApp.update["tagline"] = values[i] 
				gotOne=True
			elif argg == "source":
				uApp.update["source"] = values[i] 
				gotOne=True
			elif argg == "description":
				uApp.update["description"] = values[i] 
				gotOne=True
			elif argg == "category":
				uApp.update["category"] = values[i] 
				gotOne=True			
			else:
				print "The key '" + argg + "' do not exsist, ignoring"			
			i+=1
		if gotOne:
			uApp.updateR()
			print "Successfully Updated " + uApp.getName(sys.argv[2])
		else:
			usage()
	else:
		usage()
				
elif sys.argv[1] == "delete":
	if len(sys.argv) > 2:
		if not uApp.hasApi():
			print "You have not provided a API key"
			print "Use 'open-uapp config api [key]' to set the api key"
			sys.exit()
		if uApp.idExist(sys.argv[2]):
			uApp.delete(sys.argv[2])
			print "Successfully Deleted " + sys.argv[2]
		else:
			print "The id " + sys.argv[2] + " do not exsist!"
	else:
		usage()
elif sys.argv[1] == "config":
	if not len(sys.argv) > 2:
		print "Configs"
		print "API: " + uApp.api
		print "repoUrl: " + uApp.repoUrl
	elif sys.argv[2] == "api":
		if len(sys.argv) <= 3:
			print "You need to provide an api key"
		else:
			uApp.api = sys.argv[3]
			uApp.saveConfig()
			print "API successfully saved"
	elif sys.argv[2] == "repoUrl":
		if len(sys.argv) <= 3:
			print "You need to provide an url"
		else:
			uApp.repoUrl = sys.argv[3]
			uApp.saveConfig()
			print "repoUrl successfully saved"
	else:
		print "Cannot find the config " + sys.argv[2]

elif sys.argv[1] == "new" or sys.argv[1] == "add":
	if sys.argv > 2:
		if not os.path.isfile(sys.argv[2]):
			print "The file " + sys.argv[2] + " do not exsist."
		uApp.new(sys.argv[2])
		print "Successfully Added " + uApp.getName
		 
elif sys.argv[1] == "list":
	uApp.get()
	for i in uApp.repo["data"]:
		print i["name"] + " | " + i["id"]
		
elif sys.argv[1] == "info":
	if len(sys.argv) > 2:
		uApp.get()
		notFound=True
		for i in uApp.repo["data"]:
			if sys.argv[2] == i["id"]:
				notFound=False
				print "Name: " + i["name"]
				print "Description: " + i["description"]
				print "Tagline: " + i["tagline"]
				print "License: " + i["license"]
				print "Author: " + i["author"]
				print "Category: " + i["category"]
		if (notFound): print "Cannot find app with a id: " + sys.argv[2]
	else:
		print "Missing appID argument"
	
elif sys.argv[1] == "loaclupdate":
	print "under deveopment"

else:
	usage()
