#!/usr/bin/env python

import sys
import os
import shutil
import openUapp
from os.path import isfile

uApp = openUapp.repo()

def usage():
	print 'Usage:'	
	print 'open-uapp update [Click package] [Optional keys splited by ,,] "[Optional values splited by ,, (in the same order as keys)]" | Edit an app'
	print 'open-uapp new [Click package] | Create a new app'
	print 'open-uapp delete [app ID] | Delete an App'
	print 'open-uapp list | List all Apps'
	print 'open-uapp info [app ID] Displays info about an App'
	print ' '
	print 'Examples:'
	print 'open-uapp update mycoolapp.click license "GPL"'
	print 'open-uapp new mycoolapp.click'
	print 'open-uapp delete openstore.mzanetti'
	print 'open-uapp list'
	print 'open-uapp info openstore.mzanetti'
	
	sys.exit()

if len(sys.argv) <= 1:
	usage()
elif sys.argv[1] == "keys":
	print "license, source, description, category, tagline"
	
elif sys.argv[1] == "update":
	if len(sys.argv) > 2:
		if not uApp.hasApi():
			print "You have not provided a API key"
			print "Use 'open-uapp config api [key]' to set the api key"
			sys.exit()
		if len(sys.argv) > 3:
			arggs=sys.argv[3].split(",,")
			values=sys.argv[4].split(",,")
			i=0
			for argg in arggs:
				if argg == "license":
					uApp.update["license"] = values[i] 
				elif argg == "tagline":
					uApp.update["tagline"] = values[i] 
				elif argg == "source":
					uApp.update["source"] = values[i] 
				elif argg == "description":
					uApp.update["description"] = values[i] 
				elif argg == "category":
					uApp.update["category"] = values[i] 	
				else:
					print "The key '" + argg + "' do not exsist, ignoring"			
				i+=1
		try:
			uApp.updateR(sys.argv[2])
			print "Successfully Updated " + uApp._id
		except ValueError as e: print e[0]
	else:
		usage()
				
elif sys.argv[1] == "delete":
	if len(sys.argv) > 2:
		if not uApp.hasApi():
			print "You have not provided a API key"
			print "Use 'open-uapp config api [key]' to set the api key"
			sys.exit()
		try:
			uApp.delete(sys.argv[2])
			print "Successfully Deleted " + sys.argv[2]
		except ValueError as e: print e[0]
	else:
		usage()
elif sys.argv[1] == "config":
	if not len(sys.argv) > 2:
		print "Configs"
		print "API: " + uApp.api
		print "repoUrl: " + uApp.repoUrl
	elif sys.argv[2] == "api":
		if len(sys.argv) <= 3:
			print "You need to provide an api key"
		else:
			uApp.api = sys.argv[3]
			uApp.saveConfig()
			print "API successfully saved"
	elif sys.argv[2] == "repoUrl":
		if len(sys.argv) <= 3:
			print "You need to provide an url"
		else:
			uApp.repoUrl = sys.argv[3]
			uApp.saveConfig()
			print "repoUrl successfully saved"
	else:
		print "Cannot find the config " + sys.argv[2]

elif sys.argv[1] == "new" or sys.argv[1] == "add":
	if not uApp.hasApi():
		print "You have not provided a API key"
		print "Use 'open-uapp config api [key]' to set the api key"
		sys.exit()
	if sys.argv > 2:
		if len(sys.argv) > 3:
			arggs=sys.argv[3].split(",,")
			values=sys.argv[4].split(",,")
			i=0
			for argg in arggs:
				if argg == "license":
					uApp.update["license"] = values[i] 
				elif argg == "tagline":
					uApp.update["tagline"] = values[i] 
				elif argg == "source":
					uApp.update["source"] = values[i] 
				elif argg == "description":
					uApp.update["description"] = values[i] 
				elif argg == "category":
					uApp.update["category"] = values[i] 	
				else:
					print "The key '" + argg + "' do not exsist, ignoring"			
				i+=1
		try: 
			uApp.new(sys.argv[2])
			print "Successfully Added new package"
		except ValueError as e: print e[0]
		 
elif sys.argv[1] == "list":
	uApp.fetch()
	for i in uApp.repo["data"]:
		print i["name"] + " | " + i["id"]
		
elif sys.argv[1] == "info":
	if len(sys.argv) > 2:
		uApp.fetch()
		notFound=True
		for i in uApp.repo["data"]:
			if sys.argv[2] == i["id"]:
				notFound=False
				if not i["name"] == "": print "Name: " + i["name"]
				if not i["description"] == "": print "Description: " + i["description"]
				if not i["tagline"] == "": print "Tagline: " + i["tagline"]
				if not i["license"] == "": print "License: " + i["license"]
				if not i["author"] == "": print "Author: " + i["author"]
				if not i["category"] == "": print "Category: " + i["category"]
		if (notFound): print "Cannot find app with a id: " + sys.argv[2]
	else:
		print "Missing appID argument"

else:
	usage()
